const https = require('https')
const {resolve} = require('path')
const Koa = require('koa')
const koaBody = require('koa-body')
const router = require('./router')
const app = new Koa()

app.use(koaBody())
app.use(router.routes()).use(router.allowedMethods())
app.listen(8843, () => console.log(`Web Run In http://localhost:8843`))
